server:
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false

mybatis:
  type-aliases-package: org.tinymin.study.employees.model

logging:
  level:
    root: INFO


